<template>
  <div class="upload-view fade-in-up-sm">
    <el-card class="upload-card glass-card card-slide-in">
      <template #header>
        <div class="card-header">
          <h2 class="card-title">Subir Nuevo Documento</h2>
        </div>
      </template>
      <el-form ref="formRef" :model="form" :rules="rules" label-width="120px" class="upload-form">
        <el-form-item label="Archivo" required>
          <el-upload ref="uploadRef" class="upload-dragger" drag :auto-upload="false" :on-change="handleFileChange" :before-upload="beforeUpload" :file-list="fileList" accept=".pdf,.doc,.docx" :limit="1">
            <el-icon class="el-icon--upload"><UploadFilled /></el-icon>
            <div class="el-upload__text">Arrastra el archivo aquí o <em>haz clic para seleccionar</em></div>
            <template #tip><div class="el-upload__tip">Solo archivos PDF, DOC, DOCX. Tamaño máximo: 10MB</div></template>
          </el-upload>
        </el-form-item>
        <el-form-item label="Título" prop="title">
          <el-input v-model="form.title" placeholder="Ingresa el título del documento" maxlength="100" show-word-limit />
        </el-form-item>
        <el-form-item label="Descripción" prop="description">
          <el-input v-model="form.description" type="textarea" :rows="3" placeholder="Describe el contenido del documento" maxlength="500" show-word-limit />
        </el-form-item>
        <el-form-item label="Usuario" prop="usuario">
          <el-input v-model="form.usuario" placeholder="Usuario que sube el documento" maxlength="50" :disabled="true" />
          <div class="help-text"><el-text type="info" size="small">Se usa automáticamente tu nombre de usuario</el-text></div>
        </el-form-item>
        <el-form-item label="Autor del Documento" prop="author">
          <el-input v-model="form.author" placeholder="Nombre del autor del libro/documento (opcional)" maxlength="50" />
          <div class="help-text"><el-text type="info" size="small">Autor del documento/libro. Si lo dejas vacío, se guardará como "Anónimo"</el-text></div>
        </el-form-item>
        <el-form-item label="Etiquetas">
          <div class="tags-section">
            <el-tag v-for="tag in form.tags" :key="tag" closable @close="removeTag(tag)" class="tag-item">{{ tag }}</el-tag>
            <el-input v-if="inputVisible" ref="inputRef" v-model="inputValue" class="tag-input" size="small" @keyup.enter="handleInputConfirm" @blur="handleInputConfirm" />
            <el-button v-else class="button-new-tag" size="small" @click="showInput">+ Nueva etiqueta</el-button>
          </div>
          <div class="help-text"><el-text type="info" size="small">Las etiquetas ayudan a otros usuarios a encontrar tu documento</el-text></div>
        </el-form-item>
        <el-form-item label="Etiquetado Automático">
          <el-switch v-model="form.autoTagging" active-text="Activar" inactive-text="Desactivar" />
          <div class="help-text"><el-text type="info" size="small">El sistema generará etiquetas automáticamente basándose en el nombre del archivo</el-text></div>
        </el-form-item>
        <el-form-item>
          <div class="form-actions">
            <el-button @click="resetForm">Limpiar</el-button>
            <el-button type="primary" @click="submitForm" :loading="uploading"><el-icon><Upload /></el-icon> Subir Documento</el-button>
          </div>
        </el-form-item>
      </el-form>
    </el-card>
    <el-card v-if="form.file" class="preview-card glass-card card-slide-in">
      <template #header><h3 class="card-title">Vista Previa</h3></template>
      <div class="preview-content">
        <div class="file-info">
          <el-icon class="file-icon"><Document /></el-icon>
          <div class="file-details">
            <h4>{{ form.file.name }}</h4>
            <p>Tipo: {{ form.fileType.toUpperCase() }}</p>
            <p>Tamaño: {{ formatFileSize(form.file.size) }}</p>
          </div>
        </div>
        <div class="auto-tags" v-if="form.autoTagging && autoGeneratedTags.length > 0">
          <h5>Etiquetas generadas automáticamente:</h5>
          <el-tag v-for="tag in autoGeneratedTags" :key="tag" size="small" type="info" class="auto-tag">{{ tag }}</el-tag>
        </div>
      </div>
    </el-card>
  </div>
</template>

<script setup>
import { ref, reactive, nextTick, onMounted, watch } from 'vue';
import { useDocumentsStore } from '@/stores/documentos';
import { useAuthStore } from '@/stores/autenticacion';
import { ElMessage } from 'element-plus';
import { Upload, UploadFilled, Document } from '@element-plus/icons-vue';
import { subirDocumento } from '@/services/servicioDocumentos';
import { generarEtiquetasAutomaticas } from '@/services/servicioEtiquetadoAutomatico';

const documentsStore = useDocumentsStore();
const authStore = useAuthStore();
const formRef = ref();
const uploadRef = ref();
const inputRef = ref();

const form = reactive({
  title: '',
  description: '',
  usuario: '',
  author: '',
  tags: [],
  autoTagging: true,
  file: null,
  fileType: ''
});

const fileList = ref([]);
const uploading = ref(false);
const inputVisible = ref(false);
const inputValue = ref('');
const autoGeneratedTags = ref([]);

onMounted(() => {
  if (authStore.usuario?.nombre) form.usuario = authStore.usuario.nombre;
});

const rules = {
  title: [{ required: true, message: 'El título es obligatorio', trigger: 'blur' }, { min: 3, max: 100, message: 'El título debe tener entre 3 y 100 caracteres', trigger: 'blur' }],
  description: [{ required: true, message: 'La descripción es obligatoria', trigger: 'blur' }, { min: 10, max: 500, message: 'La descripción debe tener entre 10 y 500 caracteres', trigger: 'blur' }],
  usuario: [{ required: true, message: 'El usuario es obligatorio', trigger: 'blur' }],
  author: [{ max: 50, message: 'El autor no puede tener más de 50 caracteres', trigger: 'blur' }]
};

const handleFileChange = (file, fileList) => {
  const rawFile = file.raw || file;
  if (!rawFile || file.status === 'fail' || fileList.length === 0) {
    form.file = null;
    form.fileType = '';
    autoGeneratedTags.value = [];
    return;
  }
  form.file = rawFile;
  form.fileType = getFileType(file.name);
  if (form.autoTagging) generarEtiquetas();
};

const generarEtiquetas = () => {
  if (!form.file) return;
  autoGeneratedTags.value = generarEtiquetasAutomaticas({ fileName: form.file.name, title: form.title, description: form.description, includeKeywords: false });
  autoGeneratedTags.value.forEach(tag => { if (!form.tags.includes(tag)) form.tags.push(tag); });
};

let timeoutId = null;
watch([() => form.title, () => form.description], () => {
  if (form.autoTagging && form.file) {
    if (timeoutId) clearTimeout(timeoutId);
    timeoutId = setTimeout(() => generarEtiquetas(), 500);
  }
});

const validateFile = (file) => {
  const extension = file.name.split('.').pop().toLowerCase();
  const validTypes = ['pdf', 'doc', 'docx'];
  const isValidType = validTypes.includes(extension) && file.size / 1024 / 1024 < 10;
  if (!isValidType) {
    ElMessage.error(extension && validTypes.includes(extension) ? 'El archivo debe ser menor a 10MB!' : 'Solo se permiten archivos PDF, DOC y DOCX!');
    return false;
  }
  return true;
};

const beforeUpload = (file) => validateFile(file);
const getFileType = (fileName) => {
  const ext = fileName.split('.').pop().toLowerCase();
  return ext === 'pdf' ? 'pdf' : (['doc', 'docx'].includes(ext) ? 'docx' : 'unknown');
};

const formatFileSize = (bytes) => {
  if (bytes === 0) return '0 Bytes';
  const k = 1024;
  const sizes = ['Bytes', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
};

const removeTag = (tag) => {
  const index = form.tags.indexOf(tag);
  if (index > -1) form.tags.splice(index, 1);
};

const showInput = () => {
  inputVisible.value = true;
  nextTick(() => inputRef.value?.focus());
};

const handleInputConfirm = () => {
  if (inputValue.value && !form.tags.includes(inputValue.value)) form.tags.push(inputValue.value);
  inputVisible.value = false;
  inputValue.value = '';
};

const resetForm = () => {
  formRef.value?.resetFields();
  Object.assign(form, { title: '', description: '', usuario: authStore.usuario?.nombre || '', author: '', tags: [], autoTagging: true, file: null, fileType: '' });
  fileList.value = [];
  autoGeneratedTags.value = [];
  uploadRef.value?.clearFiles();
};

const submitForm = async () => {
  if (!form.file) {
    ElMessage.error('Por favor selecciona un archivo');
    return;
  }
  try {
    await formRef.value?.validate();
  } catch {
    ElMessage.error('Por favor completa todos los campos requeridos');
    return;
  }
  uploading.value = true;
  try {
    const formData = new FormData();
    formData.append('file', form.file);
    formData.append('title', form.title);
    formData.append('description', form.description);
    formData.append('usuario', form.usuario);
    formData.append('author', form.author || 'Anónimo');
    formData.append('tags', JSON.stringify(form.tags));
    const data = await subirDocumento(formData);
    if (data.document) {
      documentsStore.addDocument({ title: form.title, description: form.description, author: form.author, fileName: form.file.name, fileType: form.fileType, tags: form.tags, fileSize: formatFileSize(form.file.size) });
    }
    ElMessage.success('Documento subido exitosamente');
    resetForm();
  } catch (error) {
    console.error('Error al subir documento:', error);
    ElMessage.error('Error al subir el documento. Por favor intenta nuevamente.');
  } finally {
    uploading.value = false;
  }
};
</script>
